// Hand-curated barrel re-export for ts-rs generated types plus a few
// hand-mirrored shapes the engine surfaces but doesn't (yet) derive
// `TS` for. Anything in `./types/*.ts` is auto-regenerated by
// `cargo test -p nexus-types --features ts` — never hand-edit those.
//
// When the Rust side adds a new `#[derive(TS)]`, re-export here and
// (if it's a request/response wrapper) wire it into the relevant
// `./<domain>.ts` API module.

export type { AlertEvent } from "./types/AlertEvent";
export type { Artifacts } from "./types/Artifacts";
export type { BBox } from "./types/BBox";
export type { Detection } from "./types/Detection";
export type { FrameMetadata } from "./types/FrameMetadata";
export type { PipelineState } from "./types/PipelineState";
export type { PipelineStatus } from "./types/PipelineStatus";
export type { PixelFormat } from "./types/PixelFormat";
export type { Severity } from "./types/Severity";
export type { StaticAnchor } from "./types/StaticAnchor";
export type { StaticAnchorsResponse } from "./types/StaticAnchorsResponse";
export type { TrackedObject } from "./types/TrackedObject";

// ---------------------------------------------------------------------------
// Auth (hand-mirrored from crates/nexus-engine/src/auth/login.rs).
// ---------------------------------------------------------------------------

export type AuthMode = "local" | "oidc" | "hybrid";

export interface AuthInfo {
  mode: AuthMode;
  allows_local: boolean;
  allows_oidc: boolean;
  oidc_display_name?: string | null;
}

export interface AuthUser {
  id: string;
  username: string;
  role: "admin" | "operator" | "viewer";
  force_password_reset?: boolean;
}

export interface TokenResponse {
  access_token: string;
  refresh_token: string;
  expires_in: number;
  refresh_expires_in: number;
  user: AuthUser;
}

// ---------------------------------------------------------------------------
// Cameras (hand-mirrored from nexus-config / nexus-engine).
// Source of truth: crates/nexus-config/src/lib.rs CameraConfig.
// ---------------------------------------------------------------------------

export interface VisualPromptRef {
  id: string;
  label: string;
}

// Mirrors the engine-side `nexus_config::ModelConfig` shape so the camera
// editor can override every structural detector field per-camera, not just
// `kind`. All fields are optional — anything the UI omits falls back to the
// engine's defaults via serde defaults on the Rust side. The index
// signature is kept for forward compat with any field the engine adds
// before the UI types are regenerated.
export interface ModelOverride {
  kind?: string;
  pack_path?: string | null;
  preset?: string;
  input_width?: number;
  input_height?: number;
  score_threshold?: number;
  top_k?: number | null;
  [k: string]: unknown;
}

export interface CameraConfig {
  /// Server-assigned i64 row id. New cameras created from the UI
  /// MUST start with `0` and call `createCamera` (POST /cameras);
  /// the engine assigns the real id from SQLite's `INTEGER
  /// PRIMARY KEY` rowid alias and returns the populated body.
  /// Subsequent edits go via `updateCamera` (PUT /cameras/{id}).
  /// Anything non-numeric in the path is rejected by the engine's
  /// `Path<i64>` extractor with HTTP 400, so the UI never invents
  /// a placeholder like `cam-<ip>` — that flow has been broken
  /// since `CameraId` switched from `String` to `i64`.
  id: number;
  name: string;
  url: string;
  enabled?: boolean;
  max_fps?: number;
  prompts?: string[];
  visual_prompts?: VisualPromptRef[];
  model_override?: ModelOverride | null;
  parking_lot_mode?: boolean;
  // Per-camera override for the engine-wide `tracker.static_object.anchor_ttl_secs`.
  // Anchors with no matching observation older than this many seconds get
  // swept on the next classify tick. Leave undefined to inherit the engine
  // default (3600s as of writing). Restart required — the supervisor
  // reads this once at start and the reconciler only respawns on URL change.
  anchor_ttl_secs?: number | null;
  zones?: ZoneConfig[];
  // Legacy / extension fields engine may include but UI doesn't yet model.
  [k: string]: unknown;
}

// ---------------------------------------------------------------------------
// Rules. Source of truth: crates/nexus-config/src/lib.rs RuleConfig.
// ---------------------------------------------------------------------------

export type RuleSeverity = "low" | "warning" | "critical";

export interface RuleConfig {
  id: string;
  name: string;
  when: string;
  severity?: RuleSeverity | string;
  /// Camera-id allow-list. Wire format is `Vec<i64>` (matches
  /// `CameraId = i64` in the engine); the UI MUST send JSON
  /// numbers, not strings — serde rejects a string array with
  /// HTTP 422 at the rule-create boundary. Use the existing
  /// numeric `CameraConfig.id` values directly.
  camera_filter?: number[] | null;
  zones?: string[] | null;
  min_track_age_ms?: number;
  consecutive_frames?: number;
  cooldown_ms?: number;
  enabled?: boolean;
  [k: string]: unknown;
}

// ---------------------------------------------------------------------------
// Rule preview / validation.
// ---------------------------------------------------------------------------

export interface CelValidateResponse {
  ok: boolean;
  error?: string | null;
}

export interface PreviewRuleRequest {
  rule: RuleConfig;
  since_ms?: number;
  until_ms?: number;
  limit?: number;
}

export interface PreviewMatch {
  motion_event_id: number;
  camera_id: string | number;
  clip_id: number | null;
  track_id: number | null;
  captured_at: string;
  label: string;
  confidence: number;
  bbox: { x1: number; y1: number; x2: number; y2: number };
}

export interface PreviewScannedLabel {
  label: string;
  count: number;
  matched: number;
  zone_filtered: number;
  label_bytes?: number | null;
}

export interface PreviewRuleResponse {
  matches: PreviewMatch[];
  scanned: number;
  window_start: string;
  window_end: string;
  limit_hit: boolean;
  scanned_labels: PreviewScannedLabel[];
  eval_errors: number;
  eval_first_error?: string | null;
  zone_filtered: number;
  effective_when: string;
  error?: string | null;
}

// ---------------------------------------------------------------------------
// Visual prompts.
// ---------------------------------------------------------------------------

export interface VisualPromptSummary {
  id: string;
  name: string;
  description?: string | null;
  label?: string | null;
  created_at?: string;
  [k: string]: unknown;
}

// Engine returns more fields (image_path, dims, etc.) on the detail view
// vs the summary, but they all flow through the `[k: string]: unknown`
// index signature on VisualPromptSummary. A bare type alias is enough.
export type VisualPrompt = VisualPromptSummary;

export interface CameraVisualPromptAttachment {
  visual_prompt_id: string;
  label: string;
}

// ---------------------------------------------------------------------------
// Discovery.
// ---------------------------------------------------------------------------

export interface DiscoverySessionCreated {
  session_id: string;
  started_at: string;
  total_targets?: number | null;
}

export interface ScanRequest {
  cidr: string;
  ports?: number[];
  concurrency?: number;
  confirm?: boolean;
}

export interface DiscoveredDevice {
  ip: string;
  port: number;
  /// Port to actually talk RTSP to. Distinct from `port` because
  /// cameras typically expose ONVIF / web on `:80` and RTSP on
  /// `:554`. Defaults to 554 in the UI when missing.
  rtsp_port?: number | null;
  kind: "rtsp" | "onvif" | string;
  vendor?: string | null;
  model?: string | null;
  hardware?: string | null;
  firmware?: string | null;
  mac?: string | null;
  rtsp_paths: string[];
  /// Verbatim WS-Discovery `XAddrs` URL (e.g.
  /// `http://192.168.1.66/onvif/device_service`). Present
  /// only when `kind === "onvif"` AND the camera advertised
  /// at least one XAddr during discovery. When present, the
  /// UI prefers `POST .../onvif-streams` over the brute-force
  /// RTSP path sweep — the camera tells us its exact profile
  /// list + RTSP URIs, no guessing.
  onvif_xaddrs?: string | null;
}

export interface DiscoverySessionView {
  session_id: string;
  state: "running" | "done" | "error" | string;
  kind: "onvif" | "scan" | string;
  started_at: string;
  total_targets?: number | null;
  scanned: number;
  found: DiscoveredDevice[];
  error?: string | null;
}

export interface ProbeRtspRequest {
  host: string;
  port: number;
  path: string;
  username?: string;
  password?: string;
}

export interface ProbeRtspSdpStream {
  codec: string;
  resolution?: string | null;
  control?: string | null;
}

export interface ProbeRtspStream {
  path: string;
  codec?: string | null;
  resolution?: string | null;
}

export interface ProbeRtspResult {
  ok: boolean;
  status: number;
  sdp_streams: ProbeRtspSdpStream[];
  path?: string | null;
  streams: ProbeRtspStream[];
}

// ---------------------------------------------------------------------------
// ONVIF Media probe — authoritative stream enumeration via the
// camera's own GetProfiles + GetStreamUri SOAP calls. Skips the
// guess-12-paths brute force entirely. Engine handler:
// `crates/nexus-engine/src/discovery/mod.rs::post_probe_onvif`.
// ---------------------------------------------------------------------------

export interface ProbeOnvifRequest {
  /// Verbatim XAddrs URL the camera advertised during
  /// WS-Discovery (carried on `DiscoveredDevice.onvif_xaddrs`).
  xaddr: string;
  /// Mandatory — `GetProfiles` is gated on every shipped
  /// camera firmware I've seen; anonymous calls return
  /// `NotAuthorized`.
  username: string;
  password: string;
}

export interface OnvifMediaStream {
  /// ONVIF profile token (e.g. `"Profile_1"`, `"MainStream"`).
  token: string;
  /// Human-readable profile name (e.g. `"mainStream"`).
  name: string;
  /// RTSP URI as the camera reports it. **Has no credentials**
  /// embedded — the UI must inject `<user>:<pass>@` between
  /// `rtsp://` and the host before calling `cameras.add`.
  uri: string;
  /// Encoding from `VideoEncoderConfiguration.Encoding`
  /// (e.g. `"H264"`, `"H265"`). May be absent on profiles
  /// without a video encoder.
  codec?: string | null;
  /// `<width>x<height>` from the profile's resolution element
  /// (e.g. `"1920x1080"`). Absent on audio-only profiles.
  resolution?: string | null;
}

export interface ProbeOnvifResult {
  /// `true` IFF `streams` is non-empty. UI falls back to the
  /// brute-force RTSP path sweep whenever this is `false`.
  ok: boolean;
  streams: OnvifMediaStream[];
  /// Operator-facing failure reason (e.g. `"NotAuthorized"`,
  /// `"connect failed: timeout"`). Logged but not surfaced
  /// to the operator unless the RTSP fallback ALSO fails.
  error?: string | null;
}

// ---------------------------------------------------------------------------
// Prompt catalog. Mirrors `crates/nexus-engine/src/models_catalog.rs`
// `ModelPromptsCatalog` / `DetectorPromptInfo` — hand-kept in lockstep.
// ---------------------------------------------------------------------------

export interface ModelPromptsGroup {
  name: string;
  labels: string[];
}

export interface ModelPromptsEntry {
  kind: string;
  /// `true` for YOLO-World / YOLOE-text detectors that accept any
  /// user-supplied prompt; `false` for fixed-vocab kinds like
  /// closed-vocab YOLO or the PPE classifier ensemble.
  open_vocab: boolean;
  /// Every label this detector kind is known to emit (closed-vocab)
  /// or every baked prompt the detector recognises (open-vocab).
  /// Empty for `mock` / `yoloe_visual` / `classifier_ensemble`.
  prompts: string[];
  /// Optional groupings the UI can render as titled chip rows.
  groups: ModelPromptsGroup[];
  /// Operator-facing description of the detector. Shown beneath the
  /// chip strip in the camera form.
  note?: string | null;
  /// `true` iff the engine router built a layer for this kind at
  /// boot. Operators who pick an unloaded kind as an override won't
  /// see it take effect until the engine restarts; the UI uses this
  /// to surface a "restart engine to activate" hint.
  loaded: boolean;
}

export interface ModelPromptsCatalog {
  /// The default `inference.model.kind` from the engine's config —
  /// the kind every camera without a `model_override` runs against.
  default_kind: string;
  /// Stable-ordered list (the array form is preferred for dropdown
  /// rendering — see `by_kind` for keyed lookup).
  kinds: ModelPromptsEntry[];
  /// Same entries as `kinds`, indexed by `kind` for O(1) lookup.
  by_kind: Record<string, ModelPromptsEntry>;
}

// ---------------------------------------------------------------------------
// System metrics. Shape matches `crates/nexus-engine/src/system_metrics.rs`
// `SystemMetrics` exactly. Hand-mirrored (no ts-rs derive yet) — keep in
// lockstep when fields are added on the Rust side.
// ---------------------------------------------------------------------------

export interface SystemMetrics {
  uptime_secs: number;
  host: SystemHostInfo;
  cpu: SystemCpuInfo;
  memory: SystemMemoryInfo;
  gpu: SystemGpuInfo | null;
  disks: SystemDiskInfo[];
  process: SystemProcessInfo;
  captured_at: string;
}

export interface SystemHostInfo {
  hostname: string | null;
  os_name: string | null;
  os_version: string | null;
  kernel_version: string | null;
  uptime_secs: number;
}

export interface SystemCpuInfo {
  count: number;
  usage_pct: number;
  per_core_pct: number[];
  frequency_mhz: number;
  load_avg_1m: number | null;
  load_avg_5m: number | null;
  load_avg_15m: number | null;
}

export interface SystemMemoryInfo {
  total_bytes: number;
  used_bytes: number;
  available_bytes: number;
  swap_total_bytes: number;
  swap_used_bytes: number;
}

export interface SystemGpuInfo {
  kind: string;
  name: string;
  mem_total_bytes: number | null;
  mem_used_bytes: number | null;
  utilisation_pct: number | null;
  temp_c: number | null;
}

export interface SystemDiskInfo {
  name: string;
  mount_point: string;
  file_system: string;
  total_bytes: number;
  available_bytes: number;
  is_removable: boolean;
}

export interface SystemProcessInfo {
  pid: number;
  rss_bytes: number;
  virtual_bytes: number;
  cpu_pct: number;
  run_time_secs: number;
}

// ---------------------------------------------------------------------------
// Backends (matches `crates/nexus-engine/src/api.rs` BackendsResponse).
// ---------------------------------------------------------------------------

export type BackendState = "idle" | "busy" | "degraded" | "error" | "Idle" | "Busy" | "Degraded" | "Error";

export interface BackendStatus {
  slot: number;
  name: string;
  state: BackendState;
  generation: number;
}

export interface BackendsResponse {
  mode: "pool" | "in_process";
  slots: BackendStatus[];
}

// ---------------------------------------------------------------------------
// Health (GET /api/health).
// ---------------------------------------------------------------------------

export interface HealthResponse {
  status: string;
  version: string;
}

// ---------------------------------------------------------------------------
// Zones (hand-mirrored from nexus-config ZoneConfig). Polygon points are
// normalised 0..1 against the source frame. Re-mirrored here because the
// Rust side hasn't grown a ts-rs derive yet.
// ---------------------------------------------------------------------------

export type ZoneKind = "inclusion" | "exclusion" | "dwell";

export interface ZoneConfig {
  id: string;
  name: string;
  polygon: Array<[number, number]>;
  kind: ZoneKind;
}

// ---------------------------------------------------------------------------
// Motion events + histogram (hand-mirrored from nexus-store / motion handler).
// ---------------------------------------------------------------------------

export type MotionEventKind = "born" | "updated" | "died";

export interface MotionEventRow {
  id: number;
  camera_id: string | number;
  clip_id: number;
  track_id: number;
  kind: MotionEventKind;
  captured_at: string;
  bbox: { x1: number; y1: number; x2: number; y2: number };
  label: string;
  confidence: number;
  attributes_json: string;
}

export interface MotionHistogramBucket {
  bucket: number;
  bucket_start: string;
  event_count: number;
  clip_count: number;
}

// ---------------------------------------------------------------------------
// Event delivery (hand-mirrored from OutboxRow in nexus-store).
// ---------------------------------------------------------------------------

export type OutboxStatus = "pending" | "sent" | "failed" | "dead" | "suppressed";

export type SuppressionReason =
  | "global_disabled"
  | "rule_disabled"
  | "off_schedule_global"
  | "off_schedule_rule";

export interface OutboxRow {
  id: number;
  event_id: string;
  sink_id: string;
  status: OutboxStatus;
  attempts: number;
  next_attempt_at: string | null;
  last_error: string | null;
  suppression_reason: SuppressionReason | null;
  created_at: string;
  delivered_at: string | null;
}

// ---------------------------------------------------------------------------
// Storage (hand-mirrored from nexus-engine /api/v1/storage*).
// ---------------------------------------------------------------------------

export type WatermarkState = "ok" | "low" | "panic";

export interface StorageLocalResponse {
  recorder_kind: string;
  panic: boolean;
  clips_dir: string;
  fs_total_bytes: number | null;
  fs_used_bytes: number | null;
  fs_free_bytes: number | null;
  free_pct: number | null;
  watermark_state: WatermarkState;
  watermark_low_pct: number;
  watermark_panic_pct: number;
  per_camera: Array<{
    camera_id: number;
    clip_count: number;
    recorded_bytes: number;
  }>;
}

export type ColdHealthStatus = "ok" | "read_only" | "unreachable" | "not_registered";

export interface ColdHealthOut {
  status: ColdHealthStatus;
  reason?: string;
}

export interface ColdStatus {
  handle: string;
  kind: string;
  throttle_bps: number;
  updated_at: string;
  pending_count: number;
  replicated_count: number;
  cold_only_count: number;
  lifetime_uploaded_bytes: number;
  health: ColdHealthOut;
}

export type BackendKind = "lan" | "gdrive" | "onedrive";

export interface StorageBackendOut {
  handle: string;
  kind: string;
  config: Record<string, unknown>;
  created_at: string;
  updated_at: string;
}

export interface UsbAttached {
  label: string;
  mount_relpath: string;
}

export interface UsbSection {
  attached: UsbAttached[];
  preferred_label: string | null;
  preferred_active: boolean;
}

export interface StorageResponse {
  hot: StorageLocalResponse;
  cold: ColdStatus | null;
  backends: StorageBackendOut[];
  cold_only_count: number;
  usb: UsbSection;
}

export interface PutBackendReq {
  kind: BackendKind;
  config: Record<string, unknown>;
}

export interface PutColdReq {
  handle: string | null;
  throttle_bps?: number;
}

export interface ColdReplicaState {
  handle: string | null;
  throttle_bps: number;
}

export interface UsbPreferredReq {
  label: string | null;
}

export interface UsbPreferredOut {
  label: string | null;
}

// ---------------------------------------------------------------------------
// OAuth (hand-mirrored from nexus-engine /api/v1/admin/oauth/*).
// ---------------------------------------------------------------------------

export type OAuthProvider = "gdrive" | "onedrive";

export interface OAuthStartReq {
  handle: string;
  client_id: string;
  client_secret: string;
  account_email?: string;
  root_folder_id?: string;
  redirect_uri: string;
}

export interface OAuthStartResp {
  authorize_url: string;
  state: string;
  expires_in_secs: number;
}

export type OAuthStatusResp =
  | { status: "pending" }
  | { status: "complete"; handle: string }
  | { status: "error"; message: string };

// ---------------------------------------------------------------------------
// Delivery (hand-mirrored from nexus-engine /api/v1/admin/delivery).
// ---------------------------------------------------------------------------

export interface DeliverySchedule {
  // [day_of_week][half_hour_slot] — day: 0=Mon..6=Sun, slot: 0..47
  grid: boolean[][];
}

export interface DeliverySettings {
  enabled: boolean;
  schedule: DeliverySchedule | null;
  timezone: string;
  updated_at: string;
}

export interface PutAdminDeliveryReq {
  enabled: boolean;
  schedule?: DeliverySchedule | null;
  timezone?: string;
}

export interface RuleDeliveryPolicy {
  enabled: boolean;
  schedule?: DeliverySchedule | null;
}

export interface RuleDeliveryResp {
  policy: RuleDeliveryPolicy | null;
  effective: RuleDeliveryPolicy;
  inherited: boolean;
}

export interface PutRuleDeliveryReq {
  policy: RuleDeliveryPolicy | null;
}

// ---------------------------------------------------------------------------
// Sink health.
// ---------------------------------------------------------------------------

export interface OutboxSinkCounts {
  sent: number;
  failed: number;
  dead: number;
  suppressed: number;
  pending: number;
}

export interface SinkHealthEntry {
  sink_id: string;
  configured: boolean;
  counts: Record<string, OutboxSinkCounts>;
}

export interface SinksHealthResp {
  windows: Array<{ label: string; secs: number }>;
  sinks: SinkHealthEntry[];
}

// ---------------------------------------------------------------------------
// Users (hand-mirrored from nexus-engine /api/v1/admin/users).
// ---------------------------------------------------------------------------

export type UserRole = "admin" | "operator" | "viewer";

export interface UserView {
  id: string;
  username: string;
  role: UserRole;
  force_password_reset: boolean;
  disabled: boolean;
  failed_login_count: number;
  locked_until: string | null;
  last_login_at: string | null;
  last_failed_login_at: string | null;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
  has_oidc: boolean;
  has_password: boolean;
}

export interface ListUsersResponse {
  users: UserView[];
}

export interface CreateUserRequest {
  username: string;
  role: UserRole;
  password?: string;
}

export interface CreateUserResponse {
  user: UserView;
  one_time_password?: string;
}

export interface UpdateUserRequest {
  role?: UserRole;
  disabled?: boolean;
}

export interface ResetPasswordResponse {
  one_time_password: string;
}

// ---------------------------------------------------------------------------
// Audit (hand-mirrored from nexus-engine /api/v1/admin/audit).
// ---------------------------------------------------------------------------

export type AuditActorKind =
  | "local_user"
  | "oidc_user"
  | "dev_token"
  | "system";

export type AuditOutcome = "success" | "failure" | "denied";

export interface AuditRowOut {
  id: number;
  actor_kind: AuditActorKind;
  actor_id: string | null;
  actor_label: string;
  action: string;
  resource_kind: string | null;
  resource_id: string | null;
  before_json: string | null;
  after_json: string | null;
  outcome: AuditOutcome;
  ip: string | null;
  user_agent: string | null;
  created_at: string;
}

export interface ListAuditResponse {
  rows: AuditRowOut[];
  limit: number;
  offset: number;
}

export interface ListAuditQuery {
  actor_id?: string;
  action?: string;
  resource_kind?: string;
  resource_id?: string;
  outcome?: AuditOutcome;
  since?: string;
  until?: string;
  limit?: number;
  offset?: number;
}

