// Ambient types matching the Rust wire types (crates/nexus-types).
//
// In M1 this file is regenerated by `cargo test --features ts-rs` against the
// derives in `crates/nexus-types/src/lib.rs`. Until that test runs, this
// hand-maintained mirror is the contract — keep it in sync with Rust.

export type CameraId = number;
export type FrameId = number;
export type TrackId = number;
export type RuleId = string;
export type EventId = string;
export type TraceId = string;

export interface BBox {
  x1: number;
  y1: number;
  x2: number;
  y2: number;
}

export interface TrackedObject {
  track_id: TrackId;
  label: string;
  confidence: number;
  bbox: BBox;
  age_frames: number;
  age_ms: number;
  attributes?: Record<string, unknown>;
}

export interface FrameMetadata {
  camera_id: CameraId;
  frame_id: FrameId;
  captured_at: string;
  width: number;
  height: number;
  trace_id: TraceId;
  objects: TrackedObject[];
}

export type Severity = "low" | "medium" | "high" | "critical";

export interface Artifacts {
  snapshot?: string;
  clip?: string;
  cloud_receipt?: string;
}

export interface AlertEvent {
  event_id: EventId;
  camera_id: CameraId;
  rule_id: RuleId;
  track_id?: TrackId | null;
  label: string;
  severity: Severity;
  bbox?: BBox | null;
  frame_id: FrameId;
  captured_at: string;
  trace_id: TraceId;
  artifacts: Artifacts;
  context?: Record<string, unknown>;
}

export type PipelineState =
  | "initializing"
  | "running"
  | "reconnecting"
  | "stopped"
  | "failed";

export interface PipelineStatus {
  camera_id: CameraId;
  state: PipelineState;
  frames_decoded: number;
  frames_detected: number;
  last_frame_at?: string | null;
  last_error?: string | null;
}

// Camera + Rule mirror the deserialized shape from the engine's TOML/DB JSON.
export interface ZoneConfig {
  id: string;
  name: string;
  polygon: [number, number][];
  kind?: "inclusion" | "exclusion" | "dwell";
}

export interface CameraConfig {
  id: CameraId;
  name: string;
  url: string;
  enabled: boolean;
  prompts?: string[];
  model_override?: ModelConfig | null;
  zones?: ZoneConfig[];
  max_fps?: number;
  /// When true, the static-object tracker filter
  /// (`tracker.static_object.*`) is enabled for this camera. Vehicles
  /// that promote to "static" are dropped from rule eval and
  /// persisted to the per-camera registry at `runtime.state_dir`.
  /// Defaults to false on the engine side.
  parking_lot_mode?: boolean;
}

export interface ModelConfig {
  kind: string;
  pack_path?: string | null;
  input_width?: number;
  input_height?: number;
  score_threshold?: number;
}

export interface RuleConfig {
  id: RuleId;
  name: string;
  camera_filter?: CameraId[] | null;
  /// Zone-id allow-list. When non-empty, the rule only fires for
  /// objects whose bbox centre falls inside at least one of these
  /// zones (the zones themselves live on each camera; the rule
  /// stores ids only and looks them up at evaluation time).
  /// `null` / omitted / empty = no zone gate.
  zones?: string[] | null;
  when: string;
  severity: Severity;
  min_track_age_ms?: number;
  consecutive_frames?: number;
  cooldown_ms?: number;
  enabled?: boolean;
}

/// M-Admin Phase 5 — `POST /api/rules/validate` response shape.
/// Always 200 OK; `ok=false` carries the CEL parser message.
export interface RuleValidateResponse {
  ok: boolean;
  error?: string;
}

/// `POST /api/rules/preview` — replays a candidate rule against
/// the last N hours of `motion_events` and returns the rows whose
/// synthetic TrackedObject matches the rule's predicate + zone
/// gate. Debounce / cooldown gates are deliberately NOT applied;
/// the preview shows raw predicate matches so the operator can
/// tune the CEL + zones in isolation. See `preview_rule` in
/// crates/nexus-engine/src/api.rs for full semantics.
export interface RulePreviewRequest {
  rule: RuleConfig;
  /// Window start, ms since Unix epoch. Defaults to until_ms - 24h.
  since_ms?: number;
  /// Window end, ms since Unix epoch. Defaults to "now".
  until_ms?: number;
  /// Hard cap on rows scanned. Default 500; clamped to [1, 5000].
  limit?: number;
}

/// One past detection that would have matched the candidate rule.
export interface RulePreviewMatch {
  motion_event_id: number;
  camera_id: CameraId;
  clip_id: ClipId;
  track_id: number;
  captured_at: string;
  label: string;
  confidence: number;
  bbox: BBox;
}

export interface RulePreviewResponse {
  matches: RulePreviewMatch[];
  scanned: number;
  window_start: string;
  window_end: string;
  limit_hit: boolean;
  /// CEL compile error, when present. `matches` is empty in that case.
  error?: string;
}

// /api/backends shape.
export type BackendStateString =
  | "initializing"
  | "ready"
  | "restarting"
  | "failed";

export interface BackendStatus {
  slot: number;
  name: string;
  state: BackendStateString;
  generation: number;
}

export interface BackendsResponse {
  mode: "in_process" | "pool";
  slots: BackendStatus[];
}

// ---------------------------------------------------------------------------
// M-Admin Phase 1B — camera discovery.
// Mirrors crates/nexus-engine/src/discovery/mod.rs verbatim. Keep
// additive-only on the engine side so the UI can survive a partial
// rollout.
// ---------------------------------------------------------------------------

export type DiscoveryKind = "onvif" | "scan";
export type DiscoveryState = "running" | "done" | "error";
export type DeviceKind = "rtsp" | "onvif";

export interface DiscoveredDevice {
  ip: string;
  port: number;
  kind: DeviceKind;
  vendor: string | null;
  model: string | null;
  hardware: string | null;
  firmware: string | null;
  mac: string | null;
  rtsp_paths: string[];
}

export interface DiscoverySession {
  id: string;
  kind: DiscoveryKind;
  state: DiscoveryState;
  started_at: string;
  finished_at: string | null;
  progress_scanned: number;
  progress_total: number;
  found: DiscoveredDevice[];
  /// Present only when `state === "error"`.
  error?: string | null;
}

export interface ScanReq {
  cidr: string;
  ports?: number[];
  concurrency?: number;
  /// Required by the engine for CIDR prefixes ≤22 (i.e. ≥1024 hosts).
  confirm?: boolean;
}

export interface SessionCreatedResp {
  session_id: string;
  estimated_total: number;
}

export interface ProbeRtspReq {
  host: string;
  port: number;
  path: string;
  username?: string;
  password?: string;
}

export interface SdpStream {
  codec: string;
  resolution?: string;
  control?: string;
}

export interface ProbeRtspResult {
  ok: boolean;
  status: number;
  sdp_streams: SdpStream[];
}

// ---------------------------------------------------------------------------
// M2.1 Stage B (B5) — motion timeline + on-disk clip storage.
// Wire shapes mirror crates/nexus-engine/src/api.rs and
// crates/nexus-store/src/motion.rs verbatim. Keep additive-only on the
// engine side so the UI can survive a partial rollout.
// ---------------------------------------------------------------------------

export type ClipId = number;
export type MotionEventId = number;

export type MotionEventKind = "born" | "updated" | "died";

export interface StorageLocalResponse {
  /// `stub` when the engine ships the placeholder recorder, `gstreamer`
  /// once the real GstClipRecorder is wired in. Drives the recorder
  /// label and gates clip playback in the UI.
  recorder_kind: string;
  /// True iff the watermark sampler has the recorder paused.
  panic: boolean;
  /// 0..=100 free percentage on the clips_dir filesystem. None on
  /// non-unix builds.
  free_pct: number | null;
  clips_dir: string;
}

// ---------------------------------------------------------------------------
// M2.2 Phase 5 — combined storage view + cold replication admin.
// Mirrors crates/nexus-engine/src/api.rs `StorageResponse`/`ColdStatus`
// /`ColdHealthOut`/`StorageBackendOut`/`PutColdReq`/`PutBackendReq`
// verbatim. Keep additive-only on the engine side.
// ---------------------------------------------------------------------------

/// Backend health pill. `serde(tag = "status")` on the Rust side, so
/// the discriminant is a plain `status` field on the wire and the
/// `reason` field is only present for the failure variants. The
/// `not_registered` variant is distinct from `unreachable` because
/// the fix is operator re-config, not waiting for a transient outage
/// to recover.
export type ColdHealthOut =
  | { status: "ok" }
  | { status: "read_only"; reason: string }
  | { status: "unreachable"; reason: string }
  | { status: "not_registered" };

/// Active cold-replication policy + live counters. `null` on
/// `StorageResponse.cold` when no cold backend is configured.
export interface ColdStatus {
  handle: string;
  /// Backend kind (`"lan"`, etc.).
  kind: string;
  throttle_bps: number;
  updated_at: string;
  /// Closed, hashed, hot-resident clips queued for upload.
  pending_count: number;
  /// Clips with a cold pointer set (still-hot OR cold-only).
  /// Strictly monotonic for a given backend.
  replicated_count: number;
  /// Clips that are cold-only (soft-evicted). First request
  /// rehydrates from cold via the Phase 4 cache job.
  cold_only_count: number;
  /// Lifetime bytes ever uploaded to cold across all clips that
  /// currently carry a cold pointer.
  lifetime_uploaded_bytes: number;
  health: ColdHealthOut;
}

/// One row of `storage_backends`. `config` is the parsed JSON blob
/// (e.g. `{"root":"/mnt/lan-archive"}` for `lan`).
export interface StorageBackendOut {
  handle: string;
  kind: string;
  config: unknown;
  created_at: string;
  updated_at: string;
}

/// Combined `GET /api/v1/storage` payload. The `hot` section is
/// intentionally a richer superset of [`StorageLocalResponse`]: it
/// carries the M2.1 fields PLUS the watermark FSM snapshot and per-
/// camera occupancy strip used by the storage tab.
export interface StorageHotSection {
  recorder_kind: string;
  panic: boolean;
  clips_dir: string;
  fs_total_bytes: number | null;
  fs_used_bytes: number | null;
  fs_free_bytes: number | null;
  free_pct: number | null;
  watermark_state: "ok" | "low" | "panic";
  watermark_low_pct: number;
  watermark_panic_pct: number;
  per_camera: PerCameraClipStats[];
}

export interface PerCameraClipStats {
  camera_id: CameraId;
  clip_count: number;
  bytes: number;
  oldest_started_at: string;
}

export interface StorageResponse {
  hot: StorageHotSection;
  cold: ColdStatus | null;
  backends: StorageBackendOut[];
  /// Top-level mirror of `cold.cold_only_count`. Surfaced even when
  /// `cold` is `null` so the storage tab can render the "N clips
  /// cold-only" subtitle for previously-replicated clips.
  cold_only_count: number;
  /// M2.2 Phase 3 — USB hot-plug visibility.
  usb: UsbSection;
}

/// Live snapshot of the engine's `usb_watch::UsbRegistry`. The
/// recorder consults the same registry at clip-open time; this
/// section lets the operator see (a) what's currently attached and
/// (b) whether the configured `preferred_usb_label` is matched
/// right now (preferred_active === true) or just listed in
/// `nexus.toml` waiting for the volume to come back.
export interface UsbSection {
  attached: UsbVolumeOut[];
  preferred_label: string | null;
  preferred_active: boolean;
}

export interface UsbVolumeOut {
  label: string;
  /// Mount path **relative to `clips_dir`** (e.g. `usb/NEXUS_VAULT`).
  mount_relpath: string;
}

/// `PUT /api/v1/admin/storage/cold` request body. `handle: null`
/// disables cold replication; omitting `throttle_bps` keeps the
/// current value (so the operator can switch backends without
/// re-specifying bandwidth).
export interface PutColdReq {
  handle: string | null;
  throttle_bps?: number | null;
}

/// `PUT /api/v1/admin/storage/backends/:handle` request body. The
/// engine builds the backend before inserting, so an invalid `kind`
/// or `config` returns 400 without dirtying the row.
export interface PutBackendReq {
  kind: string;
  config: unknown;
}

// ---------------------------------------------------------------------------
// M2.2 closeout — OAuth 3-leg auth-code flow for cloud cold-storage.
// Mirrors crates/nexus-engine/src/api.rs `StartOAuthReq`/`StartOAuthResp`
// /`OAuthStatusResp` (kept in lock-step; additive-only).
// ---------------------------------------------------------------------------

/// `POST /api/v1/admin/oauth/{provider}/start` body. `provider` is
/// derived from the URL path. The handle/client_id/client_secret are
/// the same values the operator would otherwise paste into the
/// add-backend form; the engine stashes them in an in-memory pending
/// session keyed by the returned `state` so the `/callback` handler
/// can finish the upsert without the UI re-sending them.
export interface OAuthStartReq {
  handle: string;
  client_id: string;
  client_secret: string;
  /// Optional `account_email` (gdrive) — passed through verbatim to
  /// the backend `config` when the callback completes.
  account_email?: string | null;
  /// Optional `root_folder_id` — same treatment as `account_email`.
  root_folder_id?: string | null;
  /// Where the provider should redirect after consent. MUST exactly
  /// match a redirect URI the operator pre-registered with the
  /// provider; the engine echoes this verbatim to the token endpoint
  /// during the code exchange.
  redirect_uri: string;
}

/// `POST /api/v1/admin/oauth/{provider}/start` response. The UI
/// opens `authorize_url` in a popup and polls `/status?state=` with
/// the `state` token until the callback completes.
export interface OAuthStartResp {
  authorize_url: string;
  state: string;
  /// Server-side TTL of the pending session, in seconds. The UI
  /// stops polling and surfaces a timeout banner when the local
  /// clock exceeds this window.
  expires_in_secs: number;
}

/// `GET /api/v1/admin/oauth/status?state=` response. Discriminated
/// by `status`; `pending` is the in-progress state, `complete`
/// arrives once `/callback` has encrypted + upserted the backend,
/// `error` is terminal (the operator hits "Connect" again).
export type OAuthStatusResp =
  | { status: "pending" }
  | { status: "complete"; handle: string }
  | { status: "error"; message: string };

export interface MotionEventRow {
  id: MotionEventId;
  camera_id: CameraId;
  clip_id: ClipId;
  track_id: TrackId;
  kind: MotionEventKind;
  captured_at: string;
  bbox: BBox;
  label: string;
  confidence: number;
  attributes_json: string;
}

/// Sparse motion-density bucket for the per-camera Timeline grid.
/// Empty intervals are NOT included; the UI fills zeros client-side.
/// `bucket_start` is the inclusive lower edge; `bucket` is the
/// zero-based offset from the request's `from`.
export interface MotionHistogramBucket {
  bucket: number;
  bucket_start: string;
  event_count: number;
  clip_count: number;
}

