// Ambient types matching the Rust wire types (crates/nexus-types).
//
// In M1 this file is regenerated by `cargo test --features ts-rs` against the
// derives in `crates/nexus-types/src/lib.rs`. Until that test runs, this
// hand-maintained mirror is the contract — keep it in sync with Rust.

export type CameraId = number;
export type FrameId = number;
export type TrackId = number;
export type RuleId = string;
export type EventId = string;
export type TraceId = string;

export type PixelFormat = "rgb24" | "bgr24" | "nv12" | "i420";

export interface BBox {
  x1: number;
  y1: number;
  x2: number;
  y2: number;
}

export interface Detection {
  label: string;
  confidence: number;
  bbox: BBox;
  attributes?: Record<string, unknown>;
}

export interface TrackedObject {
  track_id: TrackId;
  label: string;
  confidence: number;
  bbox: BBox;
  age_frames: number;
  age_ms: number;
  attributes?: Record<string, unknown>;
}

export interface FrameMetadata {
  camera_id: CameraId;
  frame_id: FrameId;
  captured_at: string;
  width: number;
  height: number;
  trace_id: TraceId;
  objects: TrackedObject[];
}

export type Severity = "low" | "medium" | "high" | "critical";

export interface Artifacts {
  snapshot?: string;
  clip?: string;
  cloud_receipt?: string;
}

export interface AlertEvent {
  event_id: EventId;
  camera_id: CameraId;
  rule_id: RuleId;
  track_id?: TrackId | null;
  label: string;
  severity: Severity;
  bbox?: BBox | null;
  frame_id: FrameId;
  captured_at: string;
  trace_id: TraceId;
  artifacts: Artifacts;
  context?: Record<string, unknown>;
}

export type PipelineState =
  | "initializing"
  | "running"
  | "reconnecting"
  | "stopped"
  | "failed";

export interface PipelineStatus {
  camera_id: CameraId;
  state: PipelineState;
  frames_decoded: number;
  frames_detected: number;
  last_frame_at?: string | null;
  last_error?: string | null;
}

// Camera + Rule mirror the deserialized shape from the engine's TOML/DB JSON.
export interface ZoneConfig {
  id: string;
  name: string;
  polygon: [number, number][];
  kind?: "inclusion" | "exclusion" | "dwell";
}

export interface CameraConfig {
  id: CameraId;
  name: string;
  url: string;
  enabled: boolean;
  prompts?: string[];
  model_override?: ModelConfig | null;
  zones?: ZoneConfig[];
  max_fps?: number;
}

export interface ModelConfig {
  kind: string;
  pack_path?: string | null;
  input_width?: number;
  input_height?: number;
  score_threshold?: number;
}

export interface RuleConfig {
  id: RuleId;
  name: string;
  camera_filter?: CameraId[] | null;
  when: string;
  severity: string;
  min_track_age_ms?: number;
  consecutive_frames?: number;
  cooldown_ms?: number;
  enabled?: boolean;
}

// /api/backends shape.
export type BackendStateString =
  | "initializing"
  | "ready"
  | "restarting"
  | "failed";

export interface BackendStatus {
  slot: number;
  name: string;
  state: BackendStateString;
  generation: number;
}

export interface BackendsResponse {
  mode: "in_process" | "pool";
  slots: BackendStatus[];
}

// ---------------------------------------------------------------------------
// M2.1 Stage B (B5) — motion timeline + on-disk clip storage.
// Wire shapes mirror crates/nexus-engine/src/api.rs and
// crates/nexus-store/src/motion.rs verbatim. Keep additive-only on the
// engine side so the UI can survive a partial rollout.
// ---------------------------------------------------------------------------

export type ClipId = number;
export type MotionEventId = number;

export type MotionEventKind = "born" | "updated" | "died";

export interface StorageLocalResponse {
  /// `stub` when the engine ships the placeholder recorder, `gstreamer`
  /// once the real GstClipRecorder is wired in. Drives the recorder
  /// label and gates clip playback in the UI.
  recorder_kind: string;
  /// True iff the watermark sampler has the recorder paused.
  panic: boolean;
  /// 0..=100 free percentage on the clips_dir filesystem. None on
  /// non-unix builds.
  free_pct: number | null;
  clips_dir: string;
}

export interface MotionEventRow {
  id: MotionEventId;
  camera_id: CameraId;
  clip_id: ClipId;
  track_id: TrackId;
  kind: MotionEventKind;
  captured_at: string;
  bbox: BBox;
  label: string;
  confidence: number;
  attributes_json: string;
}

