//! M6 Phase 2 Step 2.2 — argon2id password hashing + policy.
//!
//! Three things live here:
//!
//! 1. **[`hash_password`]** — produces a self-describing PHC
//!    string (`$argon2id$v=19$m=19456,t=2,p=1$<salt>$<hash>`) that
//!    embeds the parameters used to compute it. We store this
//!    verbatim in `users.password_hash`. Parameter changes (when
//!    OWASP bumps the baseline) auto-migrate on next login:
//!    [`verify_password`] reads the embedded params from the
//!    stored hash, so old hashes keep working, and the login
//!    handler can opportunistically re-hash with the new
//!    defaults when a verify succeeds.
//!
//! 2. **[`verify_password`]** — constant-time check via the
//!    `argon2` crate. Returns `bool` rather than `Result` so
//!    the login handler can't accidentally branch on the error
//!    text (which would be a side-channel on whether the hash
//!    was even parseable).
//!
//! 3. **[`check_password_policy`]** — synchronous,
//!    no-allocations-on-the-happy-path policy enforcement:
//!    minimum length (12, the OWASP-2024 recommendation), and
//!    a curated common-password denylist embedded at compile
//!    time (`common_passwords.txt`, ~1260 entries: the full
//!    SecLists xato-net top-1000 plus hand-curated 12+ char
//!    variants like `password1234` that are reachable past the
//!    length check). The policy is intentionally minimal — no
//!    character-class theatre, no max length — matching modern
//!    NIST SP 800-63B guidance.
//!
//! ## Why argon2id's defaults
//!
//! The `argon2` crate's `Default::default()` corresponds to
//! `m_cost = 19_456` (19 MiB), `t_cost = 2`, `p_cost = 1`. This
//! is the OWASP-2024 baseline for argon2id and is what the M6
//! design doc calls out. A test below asserts the defaults
//! match — if a future bump weakens them, the test fires.
//!
//! ## What this module does NOT do
//!
//! * **Lockout / rate-limit.** That's `auth::lockout`
//!   (Phase 2 Step 2.3). This module is policy-free at the
//!   "too many attempts" axis.
//! * **Session issuance.** That's `auth::sessions`
//!   (Phase 2 Step 2.4). This module returns / consumes raw
//!   PHC strings; the login handler is what wires verification
//!   to JWT minting.
//! * **Password generation.** First-boot bootstrap (Step 2.6)
//!   uses [`auth_bootstrap::generate_token`] for its one-time
//!   24-byte URL-safe password; that token bypasses the policy
//!   check because it's generated by us, not the user.

use std::collections::HashSet;
use std::sync::OnceLock;

use argon2::{
    password_hash::{rand_core::OsRng, PasswordHash, PasswordHasher, PasswordVerifier, SaltString},
    Argon2,
};

/// Minimum password length in characters. Counted as Unicode
/// scalar values via [`str::chars`], so `"a̐é"` is 2 — the
/// NIST guidance is about typed length, not bytes.
///
/// The OWASP "Authentication Cheat Sheet" recommends ≥ 12 for
/// memorised secrets when complexity rules are NOT enforced;
/// that's our regime. Increasing this is a deliberate forward
/// migration (existing hashes keep working, but the next time
/// the user types their password — at login or change — the
/// new minimum applies).
pub const MIN_PASSWORD_LEN: usize = 12;

/// Fault paths surfaced from [`hash_password`]. The
/// `Argon2(String)` variant is the bag for the argon2 crate's
/// own error type, which is `!Send` in older versions; flatten
/// to `String` so callers can wrap into `anyhow::Error` /
/// thiserror without trait juggling.
#[derive(Debug, thiserror::Error)]
pub enum PasswordError {
    #[error("argon2: {0}")]
    Argon2(String),
    #[error("policy: {0}")]
    Policy(#[from] PasswordPolicyError),
}

/// Why a candidate password was rejected. Translated by the
/// HTTP layer into a 400 with a structured `{"error": ...}`
/// body so the UI can render specific guidance.
#[derive(Debug, thiserror::Error, PartialEq, Eq)]
pub enum PasswordPolicyError {
    #[error("password must be at least {MIN_PASSWORD_LEN} characters")]
    TooShort,
    #[error("password is on the common-password denylist")]
    Common,
}

/// Enforce password policy on a candidate plaintext. Cheap and
/// allocation-free on the happy path: the common-password set is
/// built once via `OnceLock`, and the membership check
/// lowercases via `to_lowercase()` only when length passed.
pub fn check_password_policy(plain: &str) -> Result<(), PasswordPolicyError> {
    if plain.chars().count() < MIN_PASSWORD_LEN {
        return Err(PasswordPolicyError::TooShort);
    }
    if is_common_password(plain) {
        return Err(PasswordPolicyError::Common);
    }
    Ok(())
}

/// Hash a candidate password with argon2id and the OWASP-2024
/// baseline parameters. Runs policy first so we never spend
/// ~100 ms hashing something the policy would reject anyway.
///
/// Returns the full PHC string (`$argon2id$v=19$m=...,t=...,p=...$...$...`).
/// Store this verbatim in `users.password_hash` — the parameters
/// are embedded so [`verify_password`] is forward-compatible.
pub fn hash_password(plain: &str) -> Result<String, PasswordError> {
    check_password_policy(plain)?;
    let salt = SaltString::generate(&mut OsRng);
    let argon2 = Argon2::default();
    let phc = argon2
        .hash_password(plain.as_bytes(), &salt)
        .map_err(|e| PasswordError::Argon2(e.to_string()))?
        .to_string();
    Ok(phc)
}

/// Constant-time verify against a stored PHC string. Returns
/// `false` for both "wrong password" AND "malformed hash" so
/// callers can't differentiate. The argon2 crate's own
/// `verify_password` uses a constant-time comparator on the
/// final hash bytes.
///
/// Does NOT run [`check_password_policy`] — the policy applies
/// to *new* passwords, not legacy ones. A user whose password
/// was set before we raised `MIN_PASSWORD_LEN` can still log
/// in; they'll be forced to change at next opportunity via the
/// `force_password_reset` flag the admin sets.
pub fn verify_password(plain: &str, phc: &str) -> bool {
    let Ok(parsed) = PasswordHash::new(phc) else {
        return false;
    };
    Argon2::default()
        .verify_password(plain.as_bytes(), &parsed)
        .is_ok()
}

// ---------------------------------------------------------------------------
// Internal: common-password denylist.
// ---------------------------------------------------------------------------

/// `true` iff the lowercased plaintext matches a denylist entry
/// exactly. The denylist is itself lowercased so we do one
/// allocation per check (the `to_lowercase()`) and no
/// case-folding on the set side.
fn is_common_password(plain: &str) -> bool {
    common_password_set().contains(plain.to_lowercase().as_str())
}

fn common_password_set() -> &'static HashSet<&'static str> {
    static SET: OnceLock<HashSet<&'static str>> = OnceLock::new();
    SET.get_or_init(|| {
        include_str!("common_passwords.txt")
            .lines()
            .map(str::trim)
            .filter(|line| !line.is_empty() && !line.starts_with('#'))
            .collect()
    })
}

// ---------------------------------------------------------------------------
// Tests.
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use argon2::{Algorithm, Params, Version};

    #[test]
    fn argon2_defaults_match_owasp_2024_baseline() {
        // The OWASP "Password Storage Cheat Sheet" baseline for
        // argon2id (2024): m_cost = 19_456 KiB (19 MiB),
        // t_cost = 2, p_cost = 1. If a future `argon2` crate
        // bump weakens these, this test fires so we can pin
        // explicit params instead of trusting Default.
        let p = Params::default();
        assert_eq!(
            p.m_cost(),
            19_456,
            "m_cost (KiB) drifted from OWASP-2024 baseline"
        );
        assert_eq!(p.t_cost(), 2, "t_cost drifted from OWASP-2024 baseline");
        assert_eq!(p.p_cost(), 1, "p_cost drifted from OWASP-2024 baseline");

        // Also pin the algorithm + version, in case Default ever
        // shifts away from argon2id v0x13. The `Argon2` struct
        // itself has no public algorithm getter, so we round-trip
        // through the PHC string to confirm the prefix.
        let a = Argon2::default();
        let salt = SaltString::generate(&mut OsRng);
        let phc = a
            .hash_password(b"long-enough-password", &salt)
            .unwrap()
            .to_string();
        assert!(phc.starts_with("$argon2id$v=19$"), "PHC prefix = {phc}");
        // And the `Algorithm` enum's `Argon2id` is the default
        // we rely on, not Argon2i/Argon2d.
        assert_eq!(Algorithm::default(), Algorithm::Argon2id);
        assert_eq!(Version::default(), Version::V0x13);
    }

    #[test]
    fn hash_and_verify_round_trip() {
        let plain = "correct-horse-battery-staple";
        let phc = hash_password(plain).expect("hash ok");
        assert!(phc.starts_with("$argon2id$"));
        assert!(verify_password(plain, &phc), "round-trip verify");
        assert!(
            !verify_password("wrong-horse-battery-staple", &phc),
            "wrong password fails"
        );
    }

    #[test]
    fn hash_produces_distinct_outputs_per_call() {
        // Salt is freshly random per call → two hashes of the
        // same password are different but both verify.
        let plain = "long-enough-distinct-test-pw";
        let a = hash_password(plain).unwrap();
        let b = hash_password(plain).unwrap();
        assert_ne!(a, b, "salts must differ");
        assert!(verify_password(plain, &a));
        assert!(verify_password(plain, &b));
    }

    #[test]
    fn verify_password_returns_false_for_malformed_hash() {
        // Returns false (not Err / panic) for garbage so the
        // caller cannot accidentally branch on "is the stored
        // hash even parseable" which would be a side-channel.
        assert!(!verify_password("anything", ""));
        assert!(!verify_password("anything", "not-a-phc-string"));
        assert!(!verify_password(
            "anything",
            "$bcrypt$v=2a$10$abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUV"
        ));
    }

    #[test]
    fn policy_rejects_short_passwords() {
        assert_eq!(
            check_password_policy("short").unwrap_err(),
            PasswordPolicyError::TooShort
        );
        // 11 chars — just under the limit.
        assert_eq!(
            check_password_policy("eleven-char").unwrap_err(),
            PasswordPolicyError::TooShort
        );
        // Exactly 12 — passes (assuming not in denylist).
        check_password_policy("zaphod-trout").expect("12 chars ok");
    }

    #[test]
    fn policy_counts_unicode_scalars_not_bytes() {
        // "über-secret" is 11 chars but >11 bytes (UTF-8). We
        // count chars, so it correctly rejects.
        assert_eq!(
            check_password_policy("über-secret").unwrap_err(),
            PasswordPolicyError::TooShort
        );
        // "über-secretz" is 12 chars → ok.
        check_password_policy("über-secretz").expect("12 unicode chars ok");
    }

    #[test]
    fn policy_rejects_common_passwords_case_insensitive() {
        // From the embedded denylist; these are all 12+ chars
        // so they get past the length check first.
        let common = [
            "password1234",
            "PASSWORD1234",
            "Password1234",
            "qwertyuiop12",
        ];
        for p in common {
            let err = check_password_policy(p).expect_err(p);
            assert_eq!(err, PasswordPolicyError::Common, "{p}");
        }
    }

    #[test]
    fn hash_password_runs_policy_first() {
        // Short → never reaches argon2.
        match hash_password("nope") {
            Err(PasswordError::Policy(PasswordPolicyError::TooShort)) => {}
            other => panic!("expected TooShort, got {other:?}"),
        }
        // Common → rejected with Common variant.
        match hash_password("password1234") {
            Err(PasswordError::Policy(PasswordPolicyError::Common)) => {}
            other => panic!("expected Common, got {other:?}"),
        }
    }

    #[test]
    fn denylist_loads_some_canonical_entries() {
        // Sanity-check that the embedded file actually parsed
        // and the worst-of-the-worst made it through the
        // include_str! → HashSet path. After the SecLists
        // top-1000 expansion the set is ~1260 entries; the
        // lower bound here is deliberately loose so that a
        // future prune (e.g. removing entries < MIN_PASSWORD_LEN
        // once we decide they have no audit value) won't trip
        // the test, but any catastrophic load failure still does.
        let set = common_password_set();
        assert!(
            set.len() > 1000,
            "denylist surprisingly small: {}",
            set.len()
        );
        for canonical in ["password1234", "qwertyuiop12", "letmein12345"] {
            assert!(set.contains(canonical), "denylist missing {canonical}");
        }
        // Spot-check that the SecLists top-1000 block landed.
        // These are short (< MIN_PASSWORD_LEN) and therefore
        // unreachable by real signups, but their presence
        // proves the embedded file includes the full corpus.
        for seclists in ["123456", "qwerty", "iloveyou", "monkey"] {
            assert!(
                set.contains(seclists),
                "SecLists top-1000 entry missing: {seclists}"
            );
        }
    }
}
