// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Artifacts } from "./Artifacts";
import type { BBox } from "./BBox";
import type { Severity } from "./Severity";

export type AlertEvent = { event_id: string, camera_id: bigint, rule_id: string, track_id: bigint | null, label: string, severity: Severity, bbox: BBox | null, frame_id: bigint, captured_at: string, trace_id: string, artifacts: Artifacts, context: Record<string, unknown>, };
