// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Artifacts = { 
/**
 * Path (or URL) of an annotated snapshot at the moment of the alert.
 */
snapshot: string | null, 
/**
 * Path of a short video clip surrounding the alert.
 */
clip: string | null, 
/**
 * Cloud handoff receipt, when applicable.
 */
cloud_receipt: string | null, };
