// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Axis-aligned bounding box in image pixels (top-left origin).
 */
export type BBox = { x1: number, y1: number, x2: number, y2: number, };
