// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BBox } from "./BBox";

export type Detection = { label: string, confidence: number, bbox: BBox, 
/**
 * Optional per-detection attributes from the backend (e.g. open-vocab
 * auxiliary scores). Kept opaque so backends can extend without
 * schema migrations.
 */
attributes: Record<string, unknown>, };
