// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PipelineState } from "./PipelineState";

export type PipelineStatus = { camera_id: bigint, state: PipelineState, frames_decoded: bigint, frames_detected: bigint, last_frame_at: string | null, last_error: string | null, };
