// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Three-role authorisation model. Lifted verbatim from M6 design:
 * `admin` (everything; only role allowed to mutate users, OIDC
 * config, storage backends, OAuth start/callback), `operator`
 * (camera/rule/zone/visual-prompt CRUD + replay + delivery
 * toggles), `viewer` (read-only — live frames, timeline, events,
 * dashboards).
 *
 * The variants have a total order via [`Role::level`] so a
 * `require_role(operator)` extractor accepts both operators and
 * admins: `role.level() >= required.level()`. The order is
 * `Viewer < Operator < Admin` — picking integer levels (10, 50,
 * 100) leaves room for future tiers without renumbering.
 *
 * Serde representation is `"admin" | "operator" | "viewer"` —
 * the same string we store in `users.role` and the
 * `audit_log.actor_label` denormalisation, and the same shape
 * the UI sees over JSON.
 */
export type Role = "admin" | "operator" | "viewer";
