// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StaticAnchor } from "./StaticAnchor";

/**
 * Returned by `GET /api/v1/cameras/:id/static-anchors`. `anchors`
 * is empty when the per-camera registry file is missing OR when the
 * camera has `behavior.parking_lot_mode = false`.
 */
export type StaticAnchorsResponse = { camera_id: bigint, anchors: Array<StaticAnchor>, };
