// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StaticAnchor = { 
/**
 * Lowercased detector label (e.g. `"vehicle.car"`, `"truck"`).
 */
label: string, 
/**
 * Centroid X in detector-frame pixels.
 */
center_x: number, 
/**
 * Centroid Y in detector-frame pixels.
 */
center_y: number, 
/**
 * Wall-clock (ms since UNIX epoch) of the most recent matching
 * observation. `null` only for anchors loaded from a registry
 * file written before the TTL sweep landed; the supervisor
 * promotes those to a real timestamp on the first matching
 * frame after restart. UI can render staleness from this value
 * (e.g. "2m ago" tooltips) and the engine prunes anchors
 * untouched for longer than `static_object.anchor_ttl_secs`.
 */
last_seen_unix_ms?: bigint, };
