// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BBox } from "./BBox";

export type TrackedObject = { track_id: bigint, label: string, confidence: number, bbox: BBox, 
/**
 * Frames since this track was first seen.
 */
age_frames: number, 
/**
 * Wall-clock age of the track in milliseconds.
 */
age_ms: bigint, 
/**
 * Tracker + annotator outputs (motion.speed_class, dwell.zone_state, …).
 */
attributes: Record<string, unknown>, };
